#!/usr/bin/env bash
# Install nginx web server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Holberton School" | sudo tee -a /var/www/html/index.html
sudo sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
touch /var/www/html/404.html
sudo echo "Ceci n'est pas une page" | sudo tee -a /var/www/html/404.html
sudo sed -i "/listen 80 default_server/a error_page 404 /404.html;" /etc/nginx/sites-available/default
sudo service nginx restart
